version: '3'
services:

  redis:
    container_name: redis
    image: redis:4-alpine
    volumes:
      - /var/lib/redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes
    restart: always

  postgres:
    container_name: kanalservis_db
    image: postgres:12.3
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env

  frontend:
    build:
      context: ./frontend
      dockerfile: .Dockerfile
    volumes:
      - react_build:/frontend/build

  backend:
    build:
      dockerfile: .Dockerfile
      context: .
    command: gunicorn kanalservis.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
      - react_build:/var/www/react
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  react_build:
