# Generated by Django 4.0.6 on 2022-07-14 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='№')),
                ('order_number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Заказ №')),
                ('dollar_price', models.DecimalField(decimal_places=0, max_digits=9, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость,$')),
                ('rubble_price', models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость, руб.')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
            ],
        ),
    ]
